### ISSUE TITLE
unable to use xclip?

### ISSUE THREAD

**Issue by joelgombin** [jennybc/reprex#53]
I used to be able to use reprex, but now for some reason it seems unable to use the clipboard, even though `xclip` is installed on my Ubuntu 16.04 machine. When I launch `reprex()` I get:

```r
No input provided via `x` or `input` and clipboard is not available.
```

Any idea what might be going on? I'd be happy to provide any information you might need for debugging purposes. I'm using the last github version of `reprex`.

**Comment by jennybc** [comment]
Can you tell if it's specific to this package?

What about when you test clipr directly, which is where I get the clipboard functionality?

Try these things:

```r
clipr::clipr_available()

## put something on clipboard
clipr::read_clip()

clipr::write_clip("can you hear me now?")
## now paste into editor
```

**Comment by joelgombin** [comment]
OK, somehow not it all works (this and reprex). Sorry for the dsturbance :/

**Comment by lepennec** [comment]
Installing `xclip` (or `xsel`) solves this issue.

**Comment by pgensler** [comment]
is it possible to have this information in the readme that for Linux machines you need ```xclip/xsel```? That way, others can see what packages this package depends on, and can easily install the dependencies if necessary (like for Linux)

**Comment by jennybc** [comment]
#105 is where I'm tracking messaging for linux. Dev version already gives instructions re: installing xlclip or xsel if the clipboard is not available. I will probably also switch over to the official doctor function in clipr itself before the next release.

**Comment by pgensler** [comment]
doctor function? I'm not seeing that listed in the latest version from clipr, so maybe I'm missing something here. If this is moving away to a more lightweight solution, great.

Generally speaking, I view it more as a courtesy to developers to put on your readme, package dependencies so that you set them up for success before actually using the function only to find out there's a problem: 
https://github.com/MilesMcBain/datapasta

Putting an error message that states 'you need x dependency for this feature' is just simply poor, and wrong in my opinion. You never set the user up for success from the beginning, by being transparent about dependencies, why crucify them even further? Nobody wants to run two functions only to find that "sorry, you played yourself and just diden't plan this far ahead to use x features". Running a function should not be like a video game, where you need x number of likes to 'unlock' a function for use.

**Comment by jennybc** [comment]
@pgensler I am getting more input from you than I need, here and, e.g., https://github.com/tidyverse/tibble/issues/331#issuecomment-343060378. I also find your wording to be very demanding and unconstructive. As if I, as package maintainer, need to explain and defend all my choices to you in a back and forth. I'm not going to keep engaging in this.

**Comment by LiNk-NY** [comment]
This wasn't working for me until I re-installed `xclip`. I am not sure why. 
```
> sudo apt install --reinstall xclip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 18.4 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 xclip amd64 0.13-1 [18.4 kB]
Fetched 18.4 kB in 0s (271 kB/s) 
(Reading database ... 391453 files and directories currently installed.)
Preparing to unpack .../xclip_0.13-1_amd64.deb ...
Unpacking xclip (0.13-1) over (0.13-1) ...
Setting up xclip (0.13-1) ...
Processing triggers for man-db (2.8.7-3) ...
```

```r
> packageVersion("clipr")
[1] '0.7.0'
```
