### ISSUE TITLE
reprex cannot render str_view

### ISSUE THREAD

**Issue by pgensler** [jennybc/reprex#78]
I'm not sure why, but seems like reprex will not render str_view via this code from stringr package:
Is this a true bug?

library(magrittr)
library(dplyr)
library(stringr)
test = data.frame(
  col1 = c(1,2,3),
  col2 = c("poop?","fo","fah"), stringsAsFactors = FALSE
)

glimpse(test)

test %>%
  #Matches uses regular expressions to find matches
  select(col2, matches("[:punct:]"))

#Regex Test:
stringr::str_view(test$col2, "[:punct:]")

Error:
Error in reprex_(r_file) : 
Cannot render this code.
Error : Functions that produce HTML output found in document targeting markdown_github output.
Please change the output type of this document to HTML. Alternatively, you can allow
HTML output in non-HTML formats by adding this option to the YAML front-matter of
your rmarkdown file:

**Comment by jennybc** [comment]
`stringr::str_view()` calls an HTML widget, so is not going to work in `reprex()`. At least not at this time.

The error you get explains the situation but is possibly confusing, because the errors from reprex and rmarkdown run together. This part comes from the reprex package:

```
Error in reprex_(r_file) :
Cannot render this code.
```

And then rmarkdown add this bit:

```
Error : Functions that produce HTML output found in document targeting markdown_github output.
Please change the output type of this document to HTML. Alternatively, you can allow
HTML output in non-HTML formats by adding this option to the YAML front-matter of
your rmarkdown file:
```

which isn't really relevant to you as a reprex user. Because right now there is no way to add arbitrary YAML front matter via `reprex()`. Even if I provided that, you would need PhantomJS installed in order for this suggestion to add `always_allow_html: yes` to accomplish anything.

A bummer, but not a bug.

**Comment by pgensler** [comment]
Thanks for the prompt response. Maybe you want to tag this as "next release" or "wont fix" so you will not forget? I know this package is not the magnitude of Pandas, but might be helpful to tag this issue as a reference for HTML widgets.

As a side note, #77 (formattable) use htmlwidgets, which actually converts the htmlwidget (and displays it properly), and renders it correctly in RStudio, but not with the reprex code.
